---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-records-config
  namespace: default
data:
  records.txt: |-
    www.google.com A
    www.amazon.com A
    kubernetes.default.svc.cluster.local A
    kube-dns.kube-system.svc.cluster.local A

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dnsperf
  name: dnsperf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsperf
  template:
    metadata:
      labels:
        app: dnsperf
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: dnsperf
        image: guessi/dnsperf
        imagePullPolicy: Always
        env:
        - name: DNSPERF_RECORDS_INPUT
          value: "/opt/records.txt"
        - name: EXTRA_ARGS
          value: "-c 1 -T 1 -l 30 -t 5 -Q 100000"
        volumeMounts:
        - mountPath: /opt/
          name: dns-records-volume
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: dns-records-config
        name: dns-records-volume
